// https://codeforces.com/gym/101309
#pragma GCC optimize("O3")
#include <bits/stdc++.h>
#define fore(i,a,b) for(int i=a,gmat=b;i<gmat;++i)
#define ALL(x) x.begin(),x.end()
using namespace std;
typedef vector<int> vi;
typedef pair<int,int> ii;

struct Card {
  int r;
  int s;

  bool operator<(Card c) const {
    return pair{r,s} < pair{c.r,c.s};
  }
  bool operator>(Card c) const {
    return pair{r,s} > pair{c.r,c.s};
  }
  bool operator==(Card c) const {
    return r == c.r && s == c.s;
  }
};

Card readCard() {
  char c0,c1;
  cin >> c0 >> c1;

  int s = c1 == 'C' ? 0
       : c1 == 'D' ? 1
       : c1 == 'H' ? 2
       : 3;

  int r;
  if (c0 >= '2' && c0 <= '9') {
    r = c0 - '2';
  }
  if (c0 == 'T') {
    r = 8;
  } else if (c0 == 'J') {
    r = 9;
  } else if (c0 == 'Q') {
    r = 10;
  } else if (c0 == 'K') {
    r = 11;
  } else if (c0 == 'A') {
    r = 12;
  }

  return {r,s};
}

vector<pair<Card,char>> card_to_char;

void init_card_to_char() {
  char a = 'A';
  fore(r,0,13) fore(s,0,4) {
    card_to_char.push_back({{r,s},a});
    if (a == 'Z') {
      a = 'a';
    } else if (a == 'z') {
      a = '0';
    } else {
      a++;
    }
  }
}

char toChar(Card c) {
  return card_to_char[c.r * 4 + c.s].second;
}

Card toCard(char a) {
  fore(i,0,52) {
    if (card_to_char[i].second == a) {
      return card_to_char[i].first;
    }
  }
}

enum Poker {
  HighCard,
  OnePair,
  TwoPair,
  ThreeOfAKind,
  Straight,
  Flush,
  FullHouse,
  FourOfAKind,
  StraightFlush
} __attribute__((packed));


struct Hand {
  array<Card, 5> cards;
  Poker pok;

  Hand(array<Card, 5> cards_) : cards(cards_) {
    sort(ALL(cards));
    reverse(ALL(cards));

    bool flush = true;
    fore(i, 1, 5) {
      if (cards[i].s != cards[0].s) {
        flush = false;
        break;
      }
    }

    array<vi, 13> per_rank;
    fore(i, 0, 5) {
      per_rank[cards[i].r].push_back(i);
    }

    array<ii, 13> size_i;
    fore(i, 0, 13) {
      size_i[i] = {per_rank[i].size(), i};
    }
    sort(ALL(size_i));
    reverse(ALL(size_i));

    // Straight flush
    if (flush) {
      // Normal
      bool straight = true;
      fore(i, 1, 5) {
        if (cards[i - 1].r != cards[i].r + 1) {
          straight = false;
          break;
        }
      }
      if (straight) {
        pok = StraightFlush;
        return;
      }

      // Starting with A
      if (cards[0].r == 12 && cards[1].r == 3 && cards[2].r == 2 && cards[3].r == 1 && cards[4].r == 0) {
        pok = StraightFlush;
        rotate(cards.begin(), cards.begin() + 1, cards.end());
        return;
      }
    }

    // Four of a kind
    if (size_i[0].first == 4) {
      array<Card, 5> new_cards;
      fore(i, 0, 4) {
        new_cards[i] = cards[per_rank[size_i[0].second][i]];
      }
      new_cards[4] = cards[per_rank[size_i[1].second][0]];
      cards = new_cards;
      pok = FourOfAKind;
      return;
    }

    // Full house
    if (size_i[0].first == 3 && size_i[1].first == 2) {
      array<Card, 5> new_cards;
      fore(i, 0, 3) {
        new_cards[i] = cards[per_rank[size_i[0].second][i]];
      }
      fore(i, 0, 2) {
        new_cards[3 + i] = cards[per_rank[size_i[1].second][i]];
      }
      cards = new_cards;
      pok = FullHouse;
      return;
    }

    // Flush
    if (flush) {
      pok = Flush;
      return;
    }

    // Straight
    {
      bool straight = true;
      fore(i, 1, 5) {
        if (cards[i - 1].r != cards[i].r + 1) {
          straight = false;
          break;
        }
      }
      if (straight) {
        pok = Straight;
        return;
      }

      // Starting with A
      if (cards[0].r == 12 && cards[1].r == 3 && cards[2].r == 2 && cards[3].r == 1 && cards[4].r == 0) {
        pok = Straight;
        rotate(cards.begin(), cards.begin() + 1, cards.end());
        return;
      }
    }

    // Three of a kind
    if (size_i[0].first == 3) {
      array<Card, 5> new_cards;
      fore(i, 0, 3) {
        new_cards[i] = cards[per_rank[size_i[0].second][i]];
      }
      new_cards[3] = cards[per_rank[size_i[1].second][0]];
      new_cards[4] = cards[per_rank[size_i[2].second][0]];
      assert(new_cards[3].r > new_cards[4].r);

      cards = new_cards;
      pok = ThreeOfAKind;
      return;
    }

    // Two pair
    if (size_i[0].first == 2 && size_i[1].first == 2) {
      array<Card, 5> new_cards;
      fore(i, 0, 2) {
        new_cards[i] = cards[per_rank[size_i[0].second][i]];
      }
      fore(i, 0, 2) {
        new_cards[2 + i] = cards[per_rank[size_i[1].second][i]];
      }
      assert(new_cards[0].r > new_cards[2].r);
      new_cards[4] = cards[per_rank[size_i[2].second][0]];

      cards = new_cards;
      pok = TwoPair;
      return;
    }

    // One pair
    if (size_i[0].first == 2) {
      array<Card, 5> new_cards;
      fore(i, 0, 2) {
        new_cards[i] = cards[per_rank[size_i[0].second][i]];
      }
      new_cards[2] = cards[per_rank[size_i[1].second][0]];
      new_cards[3] = cards[per_rank[size_i[2].second][0]];
      new_cards[4] = cards[per_rank[size_i[3].second][0]];
      assert(new_cards[2].r > new_cards[3].r);
      assert(new_cards[3].r > new_cards[4].r);

      cards = new_cards;
      pok = OnePair;
      return;
    }

    // Else
    pok = HighCard;
  }

  bool operator==(Hand h) const {
    return pok == h.pok && cards == h.cards;
  }

};

int cmp(const Hand& a,const Hand& b) {
  if (a.pok < b.pok) {
    return -1;
  } else if (a.pok > b.pok) {
    return 1;
  }

  fore(i,0,5) {
    if (a.cards[i].r < b.cards[i].r) {
      return -1;
    } else if (a.cards[i].r > b.cards[i].r) {
      return 1;
    }
  }

  return 0;
}


void hardCode() {
  vector<Card> cards;
  fore(r,0,13) fore(s,0,4) {
    cards.push_back({r,s});
  }

  int n_cards = cards.size();

  vector<Hand> hands;
  hands.reserve(2598960);
  fore(i,0,n_cards) fore(j,0,i) fore(k,0,j) fore(l,0,k) fore(m,0,l) {
    array<Card,5> this_hand = {cards[i],cards[j],cards[k],cards[l],cards[m]};
    hands.push_back(Hand(this_hand));
  }

  vi hands_i = vi(hands.size());
  iota(ALL(hands_i),0);

  cerr << "Sorting" << endl;

  sort(ALL(hands_i),[&](const int& a,const int& b) {
    int c = cmp(hands[a],hands[b]);
    return c == -1 || (c == 0 && a < b);
  });

  cerr << "Sorted" << endl;

  fore(j, 0, 5) {
    cout << toChar(hands[hands_i[0]].cards[j]);
  }

  cerr << "gafdsf" << endl;

  fore(i,0,hands.size() - 1) {
    int c = cmp(hands[hands_i[i]],hands[hands_i[i + 1]]);
    if (c == -1) {
      fore(j, 0, 5) {
        cout << toChar(hands[hands_i[i + 1]].cards[j]);
      }
      cerr << i << endl;
    }
  }
}

string str = "UMIEBUQIEBUQMEBUQMIBYMIEBYQIEBYQMEBYQMIBYQMIFYUIEBYUMEBYUMIBYUMIFYUQEBYUQIBYUQIFYUQMBYUQMFcMIEBcQIEBcQMEBcQMIBcQMIFcUIEBcUMEBcUMIBcUMIFcUQEBcUQIBcUQIFcUQMBcUQMFcUQMJcYIEBcYMEBcYMIBcYMIFcYQEBcYQIBcYQIFcYQMBcYQMFcYQMJcYUEBcYUIBcYUIFcYUMBcYUMFcYUMJcYUQBcYUQFcYUQJgMIEBgQIEBgQMEBgQMIBgQMIFgUIEBgUMEBgUMIBgUMIFgUQEBgUQIBgUQIFgUQMBgUQMFgUQMJgYIEBgYMEBgYMIBgYMIFgYQEBgYQIBgYQIFgYQMBgYQMFgYQMJgYUEBgYUIBgYUIFgYUMBgYUMFgYUMJgYUQBgYUQFgYUQJgYUQNgcIEBgcMEBgcMIBgcMIFgcQEBgcQIBgcQIFgcQMBgcQMFgcQMJgcUEBgcUIBgcUIFgcUMBgcUMFgcUMJgcUQBgcUQFgcUQJgcUQNgcYEBgcYIBgcYIFgcYMBgcYMFgcYMJgcYQBgcYQFgcYQJgcYQNgcYUBgcYUFgcYUJgcYUNkMIEBkQIEBkQMEBkQMIBkQMIFkUIEBkUMEBkUMIBkUMIFkUQEBkUQIBkUQIFkUQMBkUQMFkUQMJkYIEBkYMEBkYMIBkYMIFkYQEBkYQIBkYQIFkYQMBkYQMFkYQMJkYUEBkYUIBkYUIFkYUMBkYUMFkYUMJkYUQBkYUQFkYUQJkYUQNkcIEBkcMEBkcMIBkcMIFkcQEBkcQIBkcQIFkcQMBkcQMFkcQMJkcUEBkcUIBkcUIFkcUMBkcUMFkcUMJkcUQBkcUQFkcUQJkcUQNkcYEBkcYIBkcYIFkcYMBkcYMFkcYMJkcYQBkcYQFkcYQJkcYQNkcYUBkcYUFkcYUJkcYUNkcYURkgIEBkgMEBkgMIBkgMIFkgQEBkgQIBkgQIFkgQMBkgQMFkgQMJkgUEBkgUIBkgUIFkgUMBkgUMFkgUMJkgUQBkgUQFkgUQJkgUQNkgYEBkgYIBkgYIFkgYMBkgYMFkgYMJkgYQBkgYQFkgYQJkgYQNkgYUBkgYUFkgYUJkgYUNkgYURkgcEBkgcIBkgcIFkgcMBkgcMFkgcMJkgcQBkgcQFkgcQJkgcQNkgcUBkgcUFkgcUJkgcUNkgcURkgcYBkgcYFkgcYJkgcYNkgcYRoMIEBoQIEBoQMEBoQMIBoQMIFoUIEBoUMEBoUMIBoUMIFoUQEBoUQIBoUQIFoUQMBoUQMFoUQMJoYIEBoYMEBoYMIBoYMIFoYQEBoYQIBoYQIFoYQMBoYQMFoYQMJoYUEBoYUIBoYUIFoYUMBoYUMFoYUMJoYUQBoYUQFoYUQJoYUQNocIEBocMEBocMIBocMIFocQEBocQIBocQIFocQMBocQMFocQMJocUEBocUIBocUIFocUMBocUMFocUMJocUQBocUQFocUQJocUQNocYEBocYIBocYIFocYMBocYMFocYMJocYQBocYQFocYQJocYQNocYUBocYUFocYUJocYUNocYURogIEBogMEBogMIBogMIFogQEBogQIBogQIFogQMBogQMFogQMJogUEBogUIBogUIFogUMBogUMFogUMJogUQBogUQFogUQJogUQNogYEBogYIBogYIFogYMBogYMFogYMJogYQBogYQFogYQJogYQNogYUBogYUFogYUJogYUNogYURogcEBogcIBogcIFogcMBogcMFogcMJogcQBogcQFogcQJogcQNogcUBogcUFogcUJogcUNogcURogcYBogcYFogcYJogcYNogcYRogcYVokIEBokMEBokMIBokMIFokQEBokQIBokQIFokQMBokQMFokQMJokUEBokUIBokUIFokUMBokUMFokUMJokUQBokUQFokUQJokUQNokYEBokYIBokYIFokYMBokYMFokYMJokYQBokYQFokYQJokYQNokYUBokYUFokYUJokYUNokYURokcEBokcIBokcIFokcMBokcMFokcMJokcQBokcQFokcQJokcQNokcUBokcUFokcUJokcUNokcURokcYBokcYFokcYJokcYNokcYRokcYVokgEBokgIBokgIFokgMBokgMFokgMJokgQBokgQFokgQJokgQNokgUBokgUFokgUJokgUNokgURokgYBokgYFokgYJokgYNokgYRokgYVokgcBokgcFokgcJokgcNokgcRokgcVsMIEBsQIEBsQMEBsQMIBsQMIFsUIEBsUMEBsUMIBsUMIFsUQEBsUQIBsUQIFsUQMBsUQMFsUQMJsYIEBsYMEBsYMIBsYMIFsYQEBsYQIBsYQIFsYQMBsYQMFsYQMJsYUEBsYUIBsYUIFsYUMBsYUMFsYUMJsYUQBsYUQFsYUQJsYUQNscIEBscMEBscMIBscMIFscQEBscQIBscQIFscQMBscQMFscQMJscUEBscUIBscUIFscUMBscUMFscUMJscUQBscUQFscUQJscUQNscYEBscYIBscYIFscYMBscYMFscYMJscYQBscYQFscYQJscYQNscYUBscYUFscYUJscYUNscYURsgIEBsgMEBsgMIBsgMIFsgQEBsgQIBsgQIFsgQMBsgQMFsgQMJsgUEBsgUIBsgUIFsgUMBsgUMFsgUMJsgUQBsgUQFsgUQJsgUQNsgYEBsgYIBsgYIFsgYMBsgYMFsgYMJsgYQBsgYQFsgYQJsgYQNsgYUBsgYUFsgYUJsgYUNsgYURsgcEBsgcIBsgcIFsgcMBsgcMFsgcMJsgcQBsgcQFsgcQJsgcQNsgcUBsgcUFsgcUJsgcUNsgcURsgcYBsgcYFsgcYJsgcYNsgcYRsgcYVskIEBskMEBskMIBskMIFskQEBskQIBskQIFskQMBskQMFskQMJskUEBskUIBskUIFskUMBskUMFskUMJskUQBskUQFskUQJskUQNskYEBskYIBskYIFskYMBskYMFskYMJskYQBskYQFskYQJskYQNskYUBskYUFskYUJskYUNskYURskcEBskcIBskcIFskcMBskcMFskcMJskcQBskcQFskcQJskcQNskcUBskcUFskcUJskcUNskcURskcYBskcYFskcYJskcYNskcYRskcYVskgEBskgIBskgIFskgMBskgMFskgMJskgQBskgQFskgQJskgQNskgUBskgUFskgUJskgUNskgURskgYBskgYFskgYJskgYNskgYRskgYVskgcBskgcFskgcJskgcNskgcRskgcVskgcZsoIEBsoMEBsoMIBsoMIFsoQEBsoQIBsoQIFsoQMBsoQMFsoQMJsoUEBsoUIBsoUIFsoUMBsoUMFsoUMJsoUQBsoUQFsoUQJsoUQNsoYEBsoYIBsoYIFsoYMBsoYMFsoYMJsoYQBsoYQFsoYQJsoYQNsoYUBsoYUFsoYUJsoYUNsoYURsocEBsocIBsocIFsocMBsocMFsocMJsocQBsocQFsocQJsocQNsocUBsocUFsocUJsocUNsocURsocYBsocYFsocYJsocYNsocYRsocYVsogEBsogIBsogIFsogMBsogMFsogMJsogQBsogQFsogQJsogQNsogUBsogUFsogUJsogUNsogURsogYBsogYFsogYJsogYNsogYRsogYVsogcBsogcFsogcJsogcNsogcRsogcVsogcZsokEBsokIBsokIFsokMBsokMFsokMJsokQBsokQFsokQJsokQNsokUBsokUFsokUJsokUNsokURsokYBsokYFsokYJsokYNsokYRsokYVsokcBsokcFsokcJsokcNsokcRsokcVsokcZsokgBsokgFsokgJsokgNsokgRsokgVsokgZwQIEBwQMEBwQMIBwQMIFwUIEBwUMEBwUMIBwUMIFwUQEBwUQIBwUQIFwUQMBwUQMFwUQMJwYIEBwYMEBwYMIBwYMIFwYQEBwYQIBwYQIFwYQMBwYQMFwYQMJwYUEBwYUIBwYUIFwYUMBwYUMFwYUMJwYUQBwYUQFwYUQJwYUQNwcIEBwcMEBwcMIBwcMIFwcQEBwcQIBwcQIFwcQMBwcQMFwcQMJwcUEBwcUIBwcUIFwcUMBwcUMFwcUMJwcUQBwcUQFwcUQJwcUQNwcYEBwcYIBwcYIFwcYMBwcYMFwcYMJwcYQBwcYQFwcYQJwcYQNwcYUBwcYUFwcYUJwcYUNwcYURwgIEBwgMEBwgMIBwgMIFwgQEBwgQIBwgQIFwgQMBwgQMFwgQMJwgUEBwgUIBwgUIFwgUMBwgUMFwgUMJwgUQBwgUQFwgUQJwgUQNwgYEBwgYIBwgYIFwgYMBwgYMFwgYMJwgYQBwgYQFwgYQJwgYQNwgYUBwgYUFwgYUJwgYUNwgYURwgcEBwgcIBwgcIFwgcMBwgcMFwgcMJwgcQBwgcQFwgcQJwgcQNwgcUBwgcUFwgcUJwgcUNwgcURwgcYBwgcYFwgcYJwgcYNwgcYRwgcYVwkIEBwkMEBwkMIBwkMIFwkQEBwkQIBwkQIFwkQMBwkQMFwkQMJwkUEBwkUIBwkUIFwkUMBwkUMFwkUMJwkUQBwkUQFwkUQJwkUQNwkYEBwkYIBwkYIFwkYMBwkYMFwkYMJwkYQBwkYQFwkYQJwkYQNwkYUBwkYUFwkYUJwkYUNwkYURwkcEBwkcIBwkcIFwkcMBwkcMFwkcMJwkcQBwkcQFwkcQJwkcQNwkcUBwkcUFwkcUJwkcUNwkcURwkcYBwkcYFwkcYJwkcYNwkcYRwkcYVwkgEBwkgIBwkgIFwkgMBwkgMFwkgMJwkgQBwkgQFwkgQJwkgQNwkgUBwkgUFwkgUJwkgUNwkgURwkgYBwkgYFwkgYJwkgYNwkgYRwkgYVwkgcBwkgcFwkgcJwkgcNwkgcRwkgcVwkgcZwoIEBwoMEBwoMIBwoMIFwoQEBwoQIBwoQIFwoQMBwoQMFwoQMJwoUEBwoUIBwoUIFwoUMBwoUMFwoUMJwoUQBwoUQFwoUQJwoUQNwoYEBwoYIBwoYIFwoYMBwoYMFwoYMJwoYQBwoYQFwoYQJwoYQNwoYUBwoYUFwoYUJwoYUNwoYURwocEBwocIBwocIFwocMBwocMFwocMJwocQBwocQFwocQJwocQNwocUBwocUFwocUJwocUNwocURwocYBwocYFwocYJwocYNwocYRwocYVwogEBwogIBwogIFwogMBwogMFwogMJwogQBwogQFwogQJwogQNwogUBwogUFwogUJwogUNwogURwogYBwogYFwogYJwogYNwogYRwogYVwogcBwogcFwogcJwogcNwogcRwogcVwogcZwokEBwokIBwokIFwokMBwokMFwokMJwokQBwokQFwokQJwokQNwokUBwokUFwokUJwokUNwokURwokYBwokYFwokYJwokYNwokYRwokYVwokcBwokcFwokcJwokcNwokcRwokcVwokcZwokgBwokgFwokgJwokgNwokgRwokgVwokgZwokgdwsIEBwsMEBwsMIBwsMIFwsQEBwsQIBwsQIFwsQMBwsQMFwsQMJwsUEBwsUIBwsUIFwsUMBwsUMFwsUMJwsUQBwsUQFwsUQJwsUQNwsYEBwsYIBwsYIFwsYMBwsYMFwsYMJwsYQBwsYQFwsYQJwsYQNwsYUBwsYUFwsYUJwsYUNwsYURwscEBwscIBwscIFwscMBwscMFwscMJwscQBwscQFwscQJwscQNwscUBwscUFwscUJwscUNwscURwscYBwscYFwscYJwscYNwscYRwscYVwsgEBwsgIBwsgIFwsgMBwsgMFwsgMJwsgQBwsgQFwsgQJwsgQNwsgUBwsgUFwsgUJwsgUNwsgURwsgYBwsgYFwsgYJwsgYNwsgYRwsgYVwsgcBwsgcFwsgcJwsgcNwsgcRwsgcVwsgcZwskEBwskIBwskIFwskMBwskMFwskMJwskQBwskQFwskQJwskQNwskUBwskUFwskUJwskUNwskURwskYBwskYFwskYJwskYNwskYRwskYVwskcBwskcFwskcJwskcNwskcRwskcVwskcZwskgBwskgFwskgJwskgNwskgRwskgVwskgZwskgdwsoEBwsoIBwsoIFwsoMBwsoMFwsoMJwsoQBwsoQFwsoQJwsoQNwsoUBwsoUFwsoUJwsoUNwsoURwsoYBwsoYFwsoYJwsoYNwsoYRwsoYVwsocBwsocFwsocJwsocNwsocRwsocVwsocZwsogBwsogFwsogJwsogNwsogRwsogVwsogZwsogdwsokBwsokFwsokJwsokNwsokRwsokVwsokZwsokdBAMIEBAQIEBAQMEBAQMIBAUIEBAUMEBAUMIBAUQEBAUQIBAUQMBAYIEBAYMEBAYMIBAYQEBAYQIBAYQMBAYUEBAYUIBAYUMBAYUQBAcIEBAcMEBAcMIBAcQEBAcQIBAcQMBAcUEBAcUIBAcUMBAcUQBAcYEBAcYIBAcYMBAcYQBAcYUBAgIEBAgMEBAgMIBAgQEBAgQIBAgQMBAgUEBAgUIBAgUMBAgUQBAgYEBAgYIBAgYMBAgYQBAgYUBAgcEBAgcIBAgcMBAgcQBAgcUBAgcYBAkIEBAkMEBAkMIBAkQEBAkQIBAkQMBAkUEBAkUIBAkUMBAkUQBAkYEBAkYIBAkYMBAkYQBAkYUBAkcEBAkcIBAkcMBAkcQBAkcUBAkcYBAkgEBAkgIBAkgMBAkgQBAkgUBAkgYBAkgcBAoIEBAoMEBAoMIBAoQEBAoQIBAoQMBAoUEBAoUIBAoUMBAoUQBAoYEBAoYIBAoYMBAoYQBAoYUBAocEBAocIBAocMBAocQBAocUBAocYBAogEBAogIBAogMBAogQBAogUBAogYBAogcBAokEBAokIBAokMBAokQBAokUBAokYBAokcBAokgBAsIEBAsMEBAsMIBAsQEBAsQIBAsQMBAsUEBAsUIBAsUMBAsUQBAsYEBAsYIBAsYMBAsYQBAsYUBAscEBAscIBAscMBAscQBAscUBAscYBAsgEBAsgIBAsgMBAsgQBAsgUBAsgYBAsgcBAskEBAskIBAskMBAskQBAskUBAskYBAskcBAskgBAsoEBAsoIBAsoMBAsoQBAsoUBAsoYBAsocBAsogBAsokBAwIEBAwMEBAwMIBAwQEBAwQIBAwQMBAwUEBAwUIBAwUMBAwUQBAwYEBAwYIBAwYMBAwYQBAwYUBAwcEBAwcIBAwcMBAwcQBAwcUBAwcYBAwgEBAwgIBAwgMBAwgQBAwgUBAwgYBAwgcBAwkEBAwkIBAwkMBAwkQBAwkUBAwkYBAwkcBAwkgBAwoEBAwoIBAwoMBAwoQBAwoUBAwoYBAwocBAwogBAwokBAwsEBAwsIBAwsMBAwsQBAwsUBAwsYBAwscBAwsgBAwskBAwsoFEMIAFEQIAFEQMAFEQMIFEUIAFEUMAFEUMIFEUQAFEUQIFEUQMFEYIAFEYMAFEYMIFEYQAFEYQIFEYQMFEYUAFEYUIFEYUMFEYUQFEcIAFEcMAFEcMIFEcQAFEcQIFEcQMFEcUAFEcUIFEcUMFEcUQFEcYAFEcYIFEcYMFEcYQFEcYUFEgIAFEgMAFEgMIFEgQAFEgQIFEgQMFEgUAFEgUIFEgUMFEgUQFEgYAFEgYIFEgYMFEgYQFEgYUFEgcAFEgcIFEgcMFEgcQFEgcUFEgcYFEkIAFEkMAFEkMIFEkQAFEkQIFEkQMFEkUAFEkUIFEkUMFEkUQFEkYAFEkYIFEkYMFEkYQFEkYUFEkcAFEkcIFEkcMFEkcQFEkcUFEkcYFEkgAFEkgIFEkgMFEkgQFEkgUFEkgYFEkgcFEoIAFEoMAFEoMIFEoQAFEoQIFEoQMFEoUAFEoUIFEoUMFEoUQFEoYAFEoYIFEoYMFEoYQFEoYUFEocAFEocIFEocMFEocQFEocUFEocYFEogAFEogIFEogMFEogQFEogUFEogYFEogcFEokAFEokIFEokMFEokQFEokUFEokYFEokcFEokgFEsIAFEsMAFEsMIFEsQAFEsQIFEsQMFEsUAFEsUIFEsUMFEsUQFEsYAFEsYIFEsYMFEsYQFEsYUFEscAFEscIFEscMFEscQFEscUFEscYFEsgAFEsgIFEsgMFEsgQFEsgUFEsgYFEsgcFEskAFEskIFEskMFEskQFEskUFEskYFEskcFEskgFEsoAFEsoIFEsoMFEsoQFEsoUFEsoYFEsocFEsogFEsokFEwIAFEwMAFEwMIFEwQAFEwQIFEwQMFEwUAFEwUIFEwUMFEwUQFEwYAFEwYIFEwYMFEwYQFEwYUFEwcAFEwcIFEwcMFEwcQFEwcUFEwcYFEwgAFEwgIFEwgMFEwgQFEwgUFEwgYFEwgcFEwkAFEwkIFEwkMFEwkQFEwkUFEwkYFEwkcFEwkgFEwoAFEwoIFEwoMFEwoQFEwoUFEwoYFEwocFEwogFEwokFEwsAFEwsIFEwsMFEwsQFEwsUFEwsYFEwscFEwsgFEwskFEwsoJIMEAJIQEAJIQMAJIQMEJIUEAJIUMAJIUMEJIUQAJIUQEJIUQMJIYEAJIYMAJIYMEJIYQAJIYQEJIYQMJIYUAJIYUEJIYUMJIYUQJIcEAJIcMAJIcMEJIcQAJIcQEJIcQMJIcUAJIcUEJIcUMJIcUQJIcYAJIcYEJIcYMJIcYQJIcYUJIgEAJIgMAJIgMEJIgQAJIgQEJIgQMJIgUAJIgUEJIgUMJIgUQJIgYAJIgYEJIgYMJIgYQJIgYUJIgcAJIgcEJIgcMJIgcQJIgcUJIgcYJIkEAJIkMAJIkMEJIkQAJIkQEJIkQMJIkUAJIkUEJIkUMJIkUQJIkYAJIkYEJIkYMJIkYQJIkYUJIkcAJIkcEJIkcMJIkcQJIkcUJIkcYJIkgAJIkgEJIkgMJIkgQJIkgUJIkgYJIkgcJIoEAJIoMAJIoMEJIoQAJIoQEJIoQMJIoUAJIoUEJIoUMJIoUQJIoYAJIoYEJIoYMJIoYQJIoYUJIocAJIocEJIocMJIocQJIocUJIocYJIogAJIogEJIogMJIogQJIogUJIogYJIogcJIokAJIokEJIokMJIokQJIokUJIokYJIokcJIokgJIsEAJIsMAJIsMEJIsQAJIsQEJIsQMJIsUAJIsUEJIsUMJIsUQJIsYAJIsYEJIsYMJIsYQJIsYUJIscAJIscEJIscMJIscQJIscUJIscYJIsgAJIsgEJIsgMJIsgQJIsgUJIsgYJIsgcJIskAJIskEJIskMJIskQJIskUJIskYJIskcJIskgJIsoAJIsoEJIsoMJIsoQJIsoUJIsoYJIsocJIsogJIsokJIwEAJIwMAJIwMEJIwQAJIwQEJIwQMJIwUAJIwUEJIwUMJIwUQJIwYAJIwYEJIwYMJIwYQJIwYUJIwcAJIwcEJIwcMJIwcQJIwcUJIwcYJIwgAJIwgEJIwgMJIwgQJIwgUJIwgYJIwgcJIwkAJIwkEJIwkMJIwkQJIwkUJIwkYJIwkcJIwkgJIwoAJIwoEJIwoMJIwoQJIwoUJIwoYJIwocJIwogJIwokJIwsAJIwsEJIwsMJIwsQJIwsUJIwsYJIwscJIwsgJIwskJIwsoNMIEANMQEANMQIANMQIENMUEANMUIANMUIENMUQANMUQENMUQINMYEANMYIANMYIENMYQANMYQENMYQINMYUANMYUENMYUINMYUQNMcEANMcIANMcIENMcQANMcQENMcQINMcUANMcUENMcUINMcUQNMcYANMcYENMcYINMcYQNMcYUNMgEANMgIANMgIENMgQANMgQENMgQINMgUANMgUENMgUINMgUQNMgYANMgYENMgYINMgYQNMgYUNMgcANMgcENMgcINMgcQNMgcUNMgcYNMkEANMkIANMkIENMkQANMkQENMkQINMkUANMkUENMkUINMkUQNMkYANMkYENMkYINMkYQNMkYUNMkcANMkcENMkcINMkcQNMkcUNMkcYNMkgANMkgENMkgINMkgQNMkgUNMkgYNMkgcNMoEANMoIANMoIENMoQANMoQENMoQINMoUANMoUENMoUINMoUQNMoYANMoYENMoYINMoYQNMoYUNMocANMocENMocINMocQNMocUNMocYNMogANMogENMogINMogQNMogUNMogYNMogcNMokANMokENMokINMokQNMokUNMokYNMokcNMokgNMsEANMsIANMsIENMsQANMsQENMsQINMsUANMsUENMsUINMsUQNMsYANMsYENMsYINMsYQNMsYUNMscANMscENMscINMscQNMscUNMscYNMsgANMsgENMsgINMsgQNMsgUNMsgYNMsgcNMskANMskENMskINMskQNMskUNMskYNMskcNMskgNMsoANMsoENMsoINMsoQNMsoUNMsoYNMsocNMsogNMsokNMwEANMwIANMwIENMwQANMwQENMwQINMwUANMwUENMwUINMwUQNMwYANMwYENMwYINMwYQNMwYUNMwcANMwcENMwcINMwcQNMwcUNMwcYNMwgANMwgENMwgINMwgQNMwgUNMwgYNMwgcNMwkANMwkENMwkINMwkQNMwkUNMwkYNMwkcNMwkgNMwoANMwoENMwoINMwoQNMwoUNMwoYNMwocNMwogNMwokNMwsANMwsENMwsINMwsQNMwsUNMwsYNMwscNMwsgNMwskNMwsoRQIEARQMEARQMIARQMIERQUEARQUIARQUIERQUMARQUMERQUMIRQYEARQYIARQYIERQYMARQYMERQYMIRQYUARQYUERQYUIRQYUMRQcEARQcIARQcIERQcMARQcMERQcMIRQcUARQcUERQcUIRQcUMRQcYARQcYERQcYIRQcYMRQcYURQgEARQgIARQgIERQgMARQgMERQgMIRQgUARQgUERQgUIRQgUMRQgYARQgYERQgYIRQgYMRQgYURQgcARQgcERQgcIRQgcMRQgcURQgcYRQkEARQkIARQkIERQkMARQkMERQkMIRQkUARQkUERQkUIRQkUMRQkYARQkYERQkYIRQkYMRQkYURQkcARQkcERQkcIRQkcMRQkcURQkcYRQkgARQkgERQkgIRQkgMRQkgURQkgYRQkgcRQoEARQoIARQoIERQoMARQoMERQoMIRQoUARQoUERQoUIRQoUMRQoYARQoYERQoYIRQoYMRQoYURQocARQocERQocIRQocMRQocURQocYRQogARQogERQogIRQogMRQogURQogYRQogcRQokARQokERQokIRQokMRQokURQokYRQokcRQokgRQsEARQsIARQsIERQsMARQsMERQsMIRQsUARQsUERQsUIRQsUMRQsYARQsYERQsYIRQsYMRQsYURQscARQscERQscIRQscMRQscURQscYRQsgARQsgERQsgIRQsgMRQsgURQsgYRQsgcRQskARQskERQskIRQskMRQskURQskYRQskcRQskgRQsoARQsoERQsoIRQsoMRQsoURQsoYRQsocRQsogRQsokRQwEARQwIARQwIERQwMARQwMERQwMIRQwUARQwUERQwUIRQwUMRQwYARQwYERQwYIRQwYMRQwYURQwcARQwcERQwcIRQwcMRQwcURQwcYRQwgARQwgERQwgIRQwgMRQwgURQwgYRQwgcRQwkARQwkERQwkIRQwkMRQwkURQwkYRQwkcRQwkgRQwoARQwoERQwoIRQwoMRQwoURQwoYRQwocRQwogRQwokRQwsARQwsERQwsIRQwsMRQwsURQwsYRQwscRQwsgRQwskRQwsoVUIEAVUMEAVUMIAVUMIEVUQEAVUQIAVUQIEVUQMAVUQMEVUQMIVUYEAVUYIAVUYIEVUYMAVUYMEVUYMIVUYQAVUYQEVUYQIVUYQMVUcEAVUcIAVUcIEVUcMAVUcMEVUcMIVUcQAVUcQEVUcQIVUcQMVUcYAVUcYEVUcYIVUcYMVUcYQVUgEAVUgIAVUgIEVUgMAVUgMEVUgMIVUgQAVUgQEVUgQIVUgQMVUgYAVUgYEVUgYIVUgYMVUgYQVUgcAVUgcEVUgcIVUgcMVUgcQVUgcYVUkEAVUkIAVUkIEVUkMAVUkMEVUkMIVUkQAVUkQEVUkQIVUkQMVUkYAVUkYEVUkYIVUkYMVUkYQVUkcAVUkcEVUkcIVUkcMVUkcQVUkcYVUkgAVUkgEVUkgIVUkgMVUkgQVUkgYVUkgcVUoEAVUoIAVUoIEVUoMAVUoMEVUoMIVUoQAVUoQEVUoQIVUoQMVUoYAVUoYEVUoYIVUoYMVUoYQVUocAVUocEVUocIVUocMVUocQVUocYVUogAVUogEVUogIVUogMVUogQVUogYVUogcVUokAVUokEVUokIVUokMVUokQVUokYVUokcVUokgVUsEAVUsIAVUsIEVUsMAVUsMEVUsMIVUsQAVUsQEVUsQIVUsQMVUsYAVUsYEVUsYIVUsYMVUsYQVUscAVUscEVUscIVUscMVUscQVUscYVUsgAVUsgEVUsgIVUsgMVUsgQVUsgYVUsgcVUskAVUskEVUskIVUskMVUskQVUskYVUskcVUskgVUsoAVUsoEVUsoIVUsoMVUsoQVUsoYVUsocVUsogVUsokVUwEAVUwIAVUwIEVUwMAVUwMEVUwMIVUwQAVUwQEVUwQIVUwQMVUwYAVUwYEVUwYIVUwYMVUwYQVUwcAVUwcEVUwcIVUwcMVUwcQVUwcYVUwgAVUwgEVUwgIVUwgMVUwgQVUwgYVUwgcVUwkAVUwkEVUwkIVUwkMVUwkQVUwkYVUwkcVUwkgVUwoAVUwoEVUwoIVUwoMVUwoQVUwoYVUwocVUwogVUwokVUwsAVUwsEVUwsIVUwsMVUwsQVUwsYVUwscVUwsgVUwskVUwsoZYIEAZYMEAZYMIAZYMIEZYQEAZYQIAZYQIEZYQMAZYQMEZYQMIZYUEAZYUIAZYUIEZYUMAZYUMEZYUMIZYUQAZYUQEZYUQIZYUQMZYcEAZYcIAZYcIEZYcMAZYcMEZYcMIZYcQAZYcQEZYcQIZYcQMZYcUAZYcUEZYcUIZYcUMZYcUQZYgEAZYgIAZYgIEZYgMAZYgMEZYgMIZYgQAZYgQEZYgQIZYgQMZYgUAZYgUEZYgUIZYgUMZYgUQZYgcAZYgcEZYgcIZYgcMZYgcQZYgcUZYkEAZYkIAZYkIEZYkMAZYkMEZYkMIZYkQAZYkQEZYkQIZYkQMZYkUAZYkUEZYkUIZYkUMZYkUQZYkcAZYkcEZYkcIZYkcMZYkcQZYkcUZYkgAZYkgEZYkgIZYkgMZYkgQZYkgUZYkgcZYoEAZYoIAZYoIEZYoMAZYoMEZYoMIZYoQAZYoQEZYoQIZYoQMZYoUAZYoUEZYoUIZYoUMZYoUQZYocAZYocEZYocIZYocMZYocQZYocUZYogAZYogEZYogIZYogMZYogQZYogUZYogcZYokAZYokEZYokIZYokMZYokQZYokUZYokcZYokgZYsEAZYsIAZYsIEZYsMAZYsMEZYsMIZYsQAZYsQEZYsQIZYsQMZYsUAZYsUEZYsUIZYsUMZYsUQZYscAZYscEZYscIZYscMZYscQZYscUZYsgAZYsgEZYsgIZYsgMZYsgQZYsgUZYsgcZYskAZYskEZYskIZYskMZYskQZYskUZYskcZYskgZYsoAZYsoEZYsoIZYsoMZYsoQZYsoUZYsocZYsogZYsokZYwEAZYwIAZYwIEZYwMAZYwMEZYwMIZYwQAZYwQEZYwQIZYwQMZYwUAZYwUEZYwUIZYwUMZYwUQZYwcAZYwcEZYwcIZYwcMZYwcQZYwcUZYwgAZYwgEZYwgIZYwgMZYwgQZYwgUZYwgcZYwkAZYwkEZYwkIZYwkMZYwkQZYwkUZYwkcZYwkgZYwoAZYwoEZYwoIZYwoMZYwoQZYwoUZYwocZYwogZYwokZYwsAZYwsEZYwsIZYwsMZYwsQZYwsUZYwscZYwsgZYwskZYwsodcIEAdcMEAdcMIAdcMIEdcQEAdcQIAdcQIEdcQMAdcQMEdcQMIdcUEAdcUIAdcUIEdcUMAdcUMEdcUMIdcUQAdcUQEdcUQIdcUQMdcYEAdcYIAdcYIEdcYMAdcYMEdcYMIdcYQAdcYQEdcYQIdcYQMdcYUAdcYUEdcYUIdcYUMdcYUQdcgEAdcgIAdcgIEdcgMAdcgMEdcgMIdcgQAdcgQEdcgQIdcgQMdcgUAdcgUEdcgUIdcgUMdcgUQdcgYAdcgYEdcgYIdcgYMdcgYQdcgYUdckEAdckIAdckIEdckMAdckMEdckMIdckQAdckQEdckQIdckQMdckUAdckUEdckUIdckUMdckUQdckYAdckYEdckYIdckYMdckYQdckYUdckgAdckgEdckgIdckgMdckgQdckgUdckgYdcoEAdcoIAdcoIEdcoMAdcoMEdcoMIdcoQAdcoQEdcoQIdcoQMdcoUAdcoUEdcoUIdcoUMdcoUQdcoYAdcoYEdcoYIdcoYMdcoYQdcoYUdcogAdcogEdcogIdcogMdcogQdcogUdcogYdcokAdcokEdcokIdcokMdcokQdcokUdcokYdcokgdcsEAdcsIAdcsIEdcsMAdcsMEdcsMIdcsQAdcsQEdcsQIdcsQMdcsUAdcsUEdcsUIdcsUMdcsUQdcsYAdcsYEdcsYIdcsYMdcsYQdcsYUdcsgAdcsgEdcsgIdcsgMdcsgQdcsgUdcsgYdcskAdcskEdcskIdcskMdcskQdcskUdcskYdcskgdcsoAdcsoEdcsoIdcsoMdcsoQdcsoUdcsoYdcsogdcsokdcwEAdcwIAdcwIEdcwMAdcwMEdcwMIdcwQAdcwQEdcwQIdcwQMdcwUAdcwUEdcwUIdcwUMdcwUQdcwYAdcwYEdcwYIdcwYMdcwYQdcwYUdcwgAdcwgEdcwgIdcwgMdcwgQdcwgUdcwgYdcwkAdcwkEdcwkIdcwkMdcwkQdcwkUdcwkYdcwkgdcwoAdcwoEdcwoIdcwoMdcwoQdcwoUdcwoYdcwogdcwokdcwsAdcwsEdcwsIdcwsMdcwsQdcwsUdcwsYdcwsgdcwskdcwsohgIEAhgMEAhgMIAhgMIEhgQEAhgQIAhgQIEhgQMAhgQMEhgQMIhgUEAhgUIAhgUIEhgUMAhgUMEhgUMIhgUQAhgUQEhgUQIhgUQMhgYEAhgYIAhgYIEhgYMAhgYMEhgYMIhgYQAhgYQEhgYQIhgYQMhgYUAhgYUEhgYUIhgYUMhgYUQhgcEAhgcIAhgcIEhgcMAhgcMEhgcMIhgcQAhgcQEhgcQIhgcQMhgcUAhgcUEhgcUIhgcUMhgcUQhgcYAhgcYEhgcYIhgcYMhgcYQhgcYUhgkEAhgkIAhgkIEhgkMAhgkMEhgkMIhgkQAhgkQEhgkQIhgkQMhgkUAhgkUEhgkUIhgkUMhgkUQhgkYAhgkYEhgkYIhgkYMhgkYQhgkYUhgkcAhgkcEhgkcIhgkcMhgkcQhgkcUhgkcYhgoEAhgoIAhgoIEhgoMAhgoMEhgoMIhgoQAhgoQEhgoQIhgoQMhgoUAhgoUEhgoUIhgoUMhgoUQhgoYAhgoYEhgoYIhgoYMhgoYQhgoYUhgocAhgocEhgocIhgocMhgocQhgocUhgocYhgokAhgokEhgokIhgokMhgokQhgokUhgokYhgokchgsEAhgsIAhgsIEhgsMAhgsMEhgsMIhgsQAhgsQEhgsQIhgsQMhgsUAhgsUEhgsUIhgsUMhgsUQhgsYAhgsYEhgsYIhgsYMhgsYQhgsYUhgscAhgscEhgscIhgscMhgscQhgscUhgscYhgskAhgskEhgskIhgskMhgskQhgskUhgskYhgskchgsoAhgsoEhgsoIhgsoMhgsoQhgsoUhgsoYhgsochgsokhgwEAhgwIAhgwIEhgwMAhgwMEhgwMIhgwQAhgwQEhgwQIhgwQMhgwUAhgwUEhgwUIhgwUMhgwUQhgwYAhgwYEhgwYIhgwYMhgwYQhgwYUhgwcAhgwcEhgwcIhgwcMhgwcQhgwcUhgwcYhgwkAhgwkEhgwkIhgwkMhgwkQhgwkUhgwkYhgwkchgwoAhgwoEhgwoIhgwoMhgwoQhgwoUhgwoYhgwochgwokhgwsAhgwsEhgwsIhgwsMhgwsQhgwsUhgwsYhgwschgwskhgwsolkIEAlkMEAlkMIAlkMIElkQEAlkQIAlkQIElkQMAlkQMElkQMIlkUEAlkUIAlkUIElkUMAlkUMElkUMIlkUQAlkUQElkUQIlkUQMlkYEAlkYIAlkYIElkYMAlkYMElkYMIlkYQAlkYQElkYQIlkYQMlkYUAlkYUElkYUIlkYUMlkYUQlkcEAlkcIAlkcIElkcMAlkcMElkcMIlkcQAlkcQElkcQIlkcQMlkcUAlkcUElkcUIlkcUMlkcUQlkcYAlkcYElkcYIlkcYMlkcYQlkcYUlkgEAlkgIAlkgIElkgMAlkgMElkgMIlkgQAlkgQElkgQIlkgQMlkgUAlkgUElkgUIlkgUMlkgUQlkgYAlkgYElkgYIlkgYMlkgYQlkgYUlkgcAlkgcElkgcIlkgcMlkgcQlkgcUlkgcYlkoEAlkoIAlkoIElkoMAlkoMElkoMIlkoQAlkoQElkoQIlkoQMlkoUAlkoUElkoUIlkoUMlkoUQlkoYAlkoYElkoYIlkoYMlkoYQlkoYUlkocAlkocElkocIlkocMlkocQlkocUlkocYlkogAlkogElkogIlkogMlkogQlkogUlkogYlkogclksEAlksIAlksIElksMAlksMElksMIlksQAlksQElksQIlksQMlksUAlksUElksUIlksUMlksUQlksYAlksYElksYIlksYMlksYQlksYUlkscAlkscElkscIlkscMlkscQlkscUlkscYlksgAlksgElksgIlksgMlksgQlksgUlksgYlksgclksoAlksoElksoIlksoMlksoQlksoUlksoYlksoclksoglkwEAlkwIAlkwIElkwMAlkwMElkwMIlkwQAlkwQElkwQIlkwQMlkwUAlkwUElkwUIlkwUMlkwUQlkwYAlkwYElkwYIlkwYMlkwYQlkwYUlkwcAlkwcElkwcIlkwcMlkwcQlkwcUlkwcYlkwgAlkwgElkwgIlkwgMlkwgQlkwgUlkwgYlkwgclkwoAlkwoElkwoIlkwoMlkwoQlkwoUlkwoYlkwoclkwoglkwsAlkwsElkwsIlkwsMlkwsQlkwsUlkwsYlkwsclkwsglkwsopoIEApoMEApoMIApoMIEpoQEApoQIApoQIEpoQMApoQMEpoQMIpoUEApoUIApoUIEpoUMApoUMEpoUMIpoUQApoUQEpoUQIpoUQMpoYEApoYIApoYIEpoYMApoYMEpoYMIpoYQApoYQEpoYQIpoYQMpoYUApoYUEpoYUIpoYUMpoYUQpocEApocIApocIEpocMApocMEpocMIpocQApocQEpocQIpocQMpocUApocUEpocUIpocUMpocUQpocYApocYEpocYIpocYMpocYQpocYUpogEApogIApogIEpogMApogMEpogMIpogQApogQEpogQIpogQMpogUApogUEpogUIpogUMpogUQpogYApogYEpogYIpogYMpogYQpogYUpogcApogcEpogcIpogcMpogcQpogcUpogcYpokEApokIApokIEpokMApokMEpokMIpokQApokQEpokQIpokQMpokUApokUEpokUIpokUMpokUQpokYApokYEpokYIpokYMpokYQpokYUpokcApokcEpokcIpokcMpokcQpokcUpokcYpokgApokgEpokgIpokgMpokgQpokgUpokgYpokgcposEAposIAposIEposMAposMEposMIposQAposQEposQIposQMposUAposUEposUIposUMposUQposYAposYEposYIposYMposYQposYUposcAposcEposcIposcMposcQposcUposcYposgAposgEposgIposgMposgQposgUposgYposgcposkAposkEposkIposkMposkQposkUposkYposkcposkgpowEApowIApowIEpowMApowMEpowMIpowQApowQEpowQIpowQMpowUApowUEpowUIpowUMpowUQpowYApowYEpowYIpowYMpowYQpowYUpowcApowcEpowcIpowcMpowcQpowcUpowcYpowgApowgEpowgIpowgMpowgQpowgUpowgYpowgcpowkApowkEpowkIpowkMpowkQpowkUpowkYpowkcpowkgpowsApowsEpowsIpowsMpowsQpowsUpowsYpowscpowsgpowsktsIEAtsMEAtsMIAtsMIEtsQEAtsQIAtsQIEtsQMAtsQMEtsQMItsUEAtsUIAtsUIEtsUMAtsUMEtsUMItsUQAtsUQEtsUQItsUQMtsYEAtsYIAtsYIEtsYMAtsYMEtsYMItsYQAtsYQEtsYQItsYQMtsYUAtsYUEtsYUItsYUMtsYUQtscEAtscIAtscIEtscMAtscMEtscMItscQAtscQEtscQItscQMtscUAtscUEtscUItscUMtscUQtscYAtscYEtscYItscYMtscYQtscYUtsgEAtsgIAtsgIEtsgMAtsgMEtsgMItsgQAtsgQEtsgQItsgQMtsgUAtsgUEtsgUItsgUMtsgUQtsgYAtsgYEtsgYItsgYMtsgYQtsgYUtsgcAtsgcEtsgcItsgcMtsgcQtsgcUtsgcYtskEAtskIAtskIEtskMAtskMEtskMItskQAtskQEtskQItskQMtskUAtskUEtskUItskUMtskUQtskYAtskYEtskYItskYMtskYQtskYUtskcAtskcEtskcItskcMtskcQtskcUtskcYtskgAtskgEtskgItskgMtskgQtskgUtskgYtskgctsoEAtsoIAtsoIEtsoMAtsoMEtsoMItsoQAtsoQEtsoQItsoQMtsoUAtsoUEtsoUItsoUMtsoUQtsoYAtsoYEtsoYItsoYMtsoYQtsoYUtsocAtsocEtsocItsocMtsocQtsocUtsocYtsogAtsogEtsogItsogMtsogQtsogUtsogYtsogctsokAtsokEtsokItsokMtsokQtsokUtsokYtsokctsokgtswEAtswIAtswIEtswMAtswMEtswMItswQAtswQEtswQItswQMtswUAtswUEtswUItswUMtswUQtswYAtswYEtswYItswYMtswYQtswYUtswcAtswcEtswcItswcMtswcQtswcUtswcYtswgAtswgEtswgItswgMtswgQtswgUtswgYtswgctswkAtswkEtswkItswkMtswkQtswkUtswkYtswkctswkgtswoAtswoEtswoItswoMtswoQtswoUtswoYtswoctswogtswokxwIEAxwMEAxwMIAxwMIExwQEAxwQIAxwQIExwQMAxwQMExwQMIxwUEAxwUIAxwUIExwUMAxwUMExwUMIxwUQAxwUQExwUQIxwUQMxwYEAxwYIAxwYIExwYMAxwYMExwYMIxwYQAxwYQExwYQIxwYQMxwYUAxwYUExwYUIxwYUMxwYUQxwcEAxwcIAxwcIExwcMAxwcMExwcMIxwcQAxwcQExwcQIxwcQMxwcUAxwcUExwcUIxwcUMxwcUQxwcYAxwcYExwcYIxwcYMxwcYQxwcYUxwgEAxwgIAxwgIExwgMAxwgMExwgMIxwgQAxwgQExwgQIxwgQMxwgUAxwgUExwgUIxwgUMxwgUQxwgYAxwgYExwgYIxwgYMxwgYQxwgYUxwgcAxwgcExwgcIxwgcMxwgcQxwgcUxwgcYxwkEAxwkIAxwkIExwkMAxwkMExwkMIxwkQAxwkQExwkQIxwkQMxwkUAxwkUExwkUIxwkUMxwkUQxwkYAxwkYExwkYIxwkYMxwkYQxwkYUxwkcAxwkcExwkcIxwkcMxwkcQxwkcUxwkcYxwkgAxwkgExwkgIxwkgMxwkgQxwkgUxwkgYxwkgcxwoEAxwoIAxwoIExwoMAxwoMExwoMIxwoQAxwoQExwoQIxwoQMxwoUAxwoUExwoUIxwoUMxwoUQxwoYAxwoYExwoYIxwoYMxwoYQxwoYUxwocAxwocExwocIxwocMxwocQxwocUxwocYxwogAxwogExwogIxwogMxwogQxwogUxwogYxwogcxwokAxwokExwokIxwokMxwokQxwokUxwokYxwokcxwokgxwsEAxwsIAxwsIExwsMAxwsMExwsMIxwsQAxwsQExwsQIxwsQMxwsUAxwsUExwsUIxwsUMxwsUQxwsYAxwsYExwsYIxwsYMxwsYQxwsYUxwscAxwscExwscIxwscMxwscQxwscUxwscYxwsgAxwsgExwsgIxwsgMxwsgQxwsgUxwsgYxwsgcxwskAxwskExwskIxwskMxwskQxwskUxwskYxwskcxwskgxwsoAxwsoExwsoIxwsoMxwsoQxwsoUxwsoYxwsocxwsogxwsokFEBAIFEBAMFEBAQFEBAUFEBAYFEBAcFEBAgFEBAkFEBAoFEBAsFEBAwJIBAEJIBAMJIBAQJIBAUJIBAYJIBAcJIBAgJIBAkJIBAoJIBAsJIBAwJIFEAJIFEMJIFEQJIFEUJIFEYJIFEcJIFEgJIFEkJIFEoJIFEsJIFEwNMBAENMBAINMBAQNMBAUNMBAYNMBAcNMBAgNMBAkNMBAoNMBAsNMBAwNMFEANMFEINMFEQNMFEUNMFEYNMFEcNMFEgNMFEkNMFEoNMFEsNMFEwNMJIANMJIENMJIQNMJIUNMJIYNMJIcNMJIgNMJIkNMJIoNMJIsNMJIwRQBAERQBAIRQBAMRQBAURQBAYRQBAcRQBAgRQBAkRQBAoRQBAsRQBAwRQFEARQFEIRQFEMRQFEURQFEYRQFEcRQFEgRQFEkRQFEoRQFEsRQFEwRQJIARQJIERQJIMRQJIURQJIYRQJIcRQJIgRQJIkRQJIoRQJIsRQJIwRQNMARQNMERQNMIRQNMURQNMYRQNMcRQNMgRQNMkRQNMoRQNMsRQNMwVUBAEVUBAIVUBAMVUBAQVUBAYVUBAcVUBAgVUBAkVUBAoVUBAsVUBAwVUFEAVUFEIVUFEMVUFEQVUFEYVUFEcVUFEgVUFEkVUFEoVUFEsVUFEwVUJIAVUJIEVUJIMVUJIQVUJIYVUJIcVUJIgVUJIkVUJIoVUJIsVUJIwVUNMAVUNMEVUNMIVUNMQVUNMYVUNMcVUNMgVUNMkVUNMoVUNMsVUNMwVURQAVURQEVURQIVURQMVURQYVURQcVURQgVURQkVURQoVURQsVURQwZYBAEZYBAIZYBAMZYBAQZYBAUZYBAcZYBAgZYBAkZYBAoZYBAsZYBAwZYFEAZYFEIZYFEMZYFEQZYFEUZYFEcZYFEgZYFEkZYFEoZYFEsZYFEwZYJIAZYJIEZYJIMZYJIQZYJIUZYJIcZYJIgZYJIkZYJIoZYJIsZYJIwZYNMAZYNMEZYNMIZYNMQZYNMUZYNMcZYNMgZYNMkZYNMoZYNMsZYNMwZYRQAZYRQEZYRQIZYRQMZYRQUZYRQcZYRQgZYRQkZYRQoZYRQsZYRQwZYVUAZYVUEZYVUIZYVUMZYVUQZYVUcZYVUgZYVUkZYVUoZYVUsZYVUwdcBAEdcBAIdcBAMdcBAQdcBAUdcBAYdcBAgdcBAkdcBAodcBAsdcBAwdcFEAdcFEIdcFEMdcFEQdcFEUdcFEYdcFEgdcFEkdcFEodcFEsdcFEwdcJIAdcJIEdcJIMdcJIQdcJIUdcJIYdcJIgdcJIkdcJIodcJIsdcJIwdcNMAdcNMEdcNMIdcNMQdcNMUdcNMYdcNMgdcNMkdcNModcNMsdcNMwdcRQAdcRQEdcRQIdcRQMdcRQUdcRQYdcRQgdcRQkdcRQodcRQsdcRQwdcVUAdcVUEdcVUIdcVUMdcVUQdcVUYdcVUgdcVUkdcVUodcVUsdcVUwdcZYAdcZYEdcZYIdcZYMdcZYQdcZYUdcZYgdcZYkdcZYodcZYsdcZYwhgBAEhgBAIhgBAMhgBAQhgBAUhgBAYhgBAchgBAkhgBAohgBAshgBAwhgFEAhgFEIhgFEMhgFEQhgFEUhgFEYhgFEchgFEkhgFEohgFEshgFEwhgJIAhgJIEhgJIMhgJIQhgJIUhgJIYhgJIchgJIkhgJIohgJIshgJIwhgNMAhgNMEhgNMIhgNMQhgNMUhgNMYhgNMchgNMkhgNMohgNMshgNMwhgRQAhgRQEhgRQIhgRQMhgRQUhgRQYhgRQchgRQkhgRQohgRQshgRQwhgVUAhgVUEhgVUIhgVUMhgVUQhgVUYhgVUchgVUkhgVUohgVUshgVUwhgZYAhgZYEhgZYIhgZYMhgZYQhgZYUhgZYchgZYkhgZYohgZYshgZYwhgdcAhgdcEhgdcIhgdcMhgdcQhgdcUhgdcYhgdckhgdcohgdcshgdcwlkBAElkBAIlkBAMlkBAQlkBAUlkBAYlkBAclkBAglkBAolkBAslkBAwlkFEAlkFEIlkFEMlkFEQlkFEUlkFEYlkFEclkFEglkFEolkFEslkFEwlkJIAlkJIElkJIMlkJIQlkJIUlkJIYlkJIclkJIglkJIolkJIslkJIwlkNMAlkNMElkNMIlkNMQlkNMUlkNMYlkNMclkNMglkNMolkNMslkNMwlkRQAlkRQElkRQIlkRQMlkRQUlkRQYlkRQclkRQglkRQolkRQslkRQwlkVUAlkVUElkVUIlkVUMlkVUQlkVUYlkVUclkVUglkVUolkVUslkVUwlkZYAlkZYElkZYIlkZYMlkZYQlkZYUlkZYclkZYglkZYolkZYslkZYwlkdcAlkdcElkdcIlkdcMlkdcQlkdcUlkdcYlkdcglkdcolkdcslkdcwlkhgAlkhgElkhgIlkhgMlkhgQlkhgUlkhgYlkhgclkhgolkhgslkhgwpoBAEpoBAIpoBAMpoBAQpoBAUpoBAYpoBAcpoBAgpoBAkpoBAspoBAwpoFEApoFEIpoFEMpoFEQpoFEUpoFEYpoFEcpoFEgpoFEkpoFEspoFEwpoJIApoJIEpoJIMpoJIQpoJIUpoJIYpoJIcpoJIgpoJIkpoJIspoJIwpoNMApoNMEpoNMIpoNMQpoNMUpoNMYpoNMcpoNMgpoNMkpoNMspoNMwpoRQApoRQEpoRQIpoRQMpoRQUpoRQYpoRQcpoRQgpoRQkpoRQspoRQwpoVUApoVUEpoVUIpoVUMpoVUQpoVUYpoVUcpoVUgpoVUkpoVUspoVUwpoZYApoZYEpoZYIpoZYMpoZYQpoZYUpoZYcpoZYgpoZYkpoZYspoZYwpodcApodcEpodcIpodcMpodcQpodcUpodcYpodcgpodckpodcspodcwpohgApohgEpohgIpohgMpohgQpohgUpohgYpohgcpohgkpohgspohgwpolkApolkEpolkIpolkMpolkQpolkUpolkYpolkcpolkgpolkspolkwtsBAEtsBAItsBAMtsBAQtsBAUtsBAYtsBActsBAgtsBAktsBAotsBAwtsFEAtsFEItsFEMtsFEQtsFEUtsFEYtsFEctsFEgtsFEktsFEotsFEwtsJIAtsJIEtsJIMtsJIQtsJIUtsJIYtsJIctsJIgtsJIktsJIotsJIwtsNMAtsNMEtsNMItsNMQtsNMUtsNMYtsNMctsNMgtsNMktsNMotsNMwtsRQAtsRQEtsRQItsRQMtsRQUtsRQYtsRQctsRQgtsRQktsRQotsRQwtsVUAtsVUEtsVUItsVUMtsVUQtsVUYtsVUctsVUgtsVUktsVUotsVUwtsZYAtsZYEtsZYItsZYMtsZYQtsZYUtsZYctsZYgtsZYktsZYotsZYwtsdcAtsdcEtsdcItsdcMtsdcQtsdcUtsdcYtsdcgtsdcktsdcotsdcwtshgAtshgEtshgItshgMtshgQtshgUtshgYtshgctshgktshgotshgwtslkAtslkEtslkItslkMtslkQtslkUtslkYtslkctslkgtslkotslkwtspoAtspoEtspoItspoMtspoQtspoUtspoYtspoctspogtspoktspowxwBAExwBAIxwBAMxwBAQxwBAUxwBAYxwBAcxwBAgxwBAkxwBAoxwBAsxwFEAxwFEIxwFEMxwFEQxwFEUxwFEYxwFEcxwFEgxwFEkxwFEoxwFEsxwJIAxwJIExwJIMxwJIQxwJIUxwJIYxwJIcxwJIgxwJIkxwJIoxwJIsxwNMAxwNMExwNMIxwNMQxwNMUxwNMYxwNMcxwNMgxwNMkxwNMoxwNMsxwRQAxwRQExwRQIxwRQMxwRQUxwRQYxwRQcxwRQgxwRQkxwRQoxwRQsxwVUAxwVUExwVUIxwVUMxwVUQxwVUYxwVUcxwVUgxwVUkxwVUoxwVUsxwZYAxwZYExwZYIxwZYMxwZYQxwZYUxwZYcxwZYgxwZYkxwZYoxwZYsxwdcAxwdcExwdcIxwdcMxwdcQxwdcUxwdcYxwdcgxwdckxwdcoxwdcsxwhgAxwhgExwhgIxwhgMxwhgQxwhgUxwhgYxwhgcxwhgkxwhgoxwhgsxwlkAxwlkExwlkIxwlkMxwlkQxwlkUxwlkYxwlkcxwlkgxwlkoxwlksxwpoAxwpoExwpoIxwpoMxwpoQxwpoUxwpoYxwpocxwpogxwpokxwposxwtsAxwtsExwtsIxwtsMxwtsQxwtsUxwtsYxwtscxwtsgxwtskxwtsoCBAIECBAMECBAMICBAQECBAQICBAQMCBAUECBAUICBAUMCBAUQCBAYECBAYICBAYMCBAYQCBAYUCBAcECBAcICBAcMCBAcQCBAcUCBAcYCBAgECBAgICBAgMCBAgQCBAgUCBAgYCBAgcCBAkECBAkICBAkMCBAkQCBAkUCBAkYCBAkcCBAkgCBAoECBAoICBAoMCBAoQCBAoUCBAoYCBAocCBAogCBAokCBAsECBAsICBAsMCBAsQCBAsUCBAsYCBAscCBAsgCBAskCBAsoCBAwECBAwICBAwMCBAwQCBAwUCBAwYCBAwcCBAwgCBAwkCBAwoCBAwsGFEIAGFEMAGFEMIGFEQAGFEQIGFEQMGFEUAGFEUIGFEUMGFEUQGFEYAGFEYIGFEYMGFEYQGFEYUGFEcAGFEcIGFEcMGFEcQGFEcUGFEcYGFEgAGFEgIGFEgMGFEgQGFEgUGFEgYGFEgcGFEkAGFEkIGFEkMGFEkQGFEkUGFEkYGFEkcGFEkgGFEoAGFEoIGFEoMGFEoQGFEoUGFEoYGFEocGFEogGFEokGFEsAGFEsIGFEsMGFEsQGFEsUGFEsYGFEscGFEsgGFEskGFEsoGFEwAGFEwIGFEwMGFEwQGFEwUGFEwYGFEwcGFEwgGFEwkGFEwoGFEwsKJIEAKJIMAKJIMEKJIQAKJIQEKJIQMKJIUAKJIUEKJIUMKJIUQKJIYAKJIYEKJIYMKJIYQKJIYUKJIcAKJIcEKJIcMKJIcQKJIcUKJIcYKJIgAKJIgEKJIgMKJIgQKJIgUKJIgYKJIgcKJIkAKJIkEKJIkMKJIkQKJIkUKJIkYKJIkcKJIkgKJIoAKJIoEKJIoMKJIoQKJIoUKJIoYKJIocKJIogKJIokKJIsAKJIsEKJIsMKJIsQKJIsUKJIsYKJIscKJIsgKJIskKJIsoKJIwAKJIwEKJIwMKJIwQKJIwUKJIwYKJIwcKJIwgKJIwkKJIwoKJIwsONMEAONMIAONMIEONMQAONMQEONMQIONMUAONMUEONMUIONMUQONMYAONMYEONMYIONMYQONMYUONMcAONMcEONMcIONMcQONMcUONMcYONMgAONMgEONMgIONMgQONMgUONMgYONMgcONMkAONMkEONMkIONMkQONMkUONMkYONMkcONMkgONMoAONMoEONMoIONMoQONMoUONMoYONMocONMogONMokONMsAONMsEONMsIONMsQONMsUONMsYONMscONMsgONMskONMsoONMwAONMwEONMwIONMwQONMwUONMwYONMwcONMwgONMwkONMwoONMwsSRQEASRQIASRQIESRQMASRQMESRQMISRQUASRQUESRQUISRQUMSRQYASRQYESRQYISRQYMSRQYUSRQcASRQcESRQcISRQcMSRQcUSRQcYSRQgASRQgESRQgISRQgMSRQgUSRQgYSRQgcSRQkASRQkESRQkISRQkMSRQkUSRQkYSRQkcSRQkgSRQoASRQoESRQoISRQoMSRQoUSRQoYSRQocSRQogSRQokSRQsASRQsESRQsISRQsMSRQsUSRQsYSRQscSRQsgSRQskSRQsoSRQwASRQwESRQwISRQwMSRQwUSRQwYSRQwcSRQwgSRQwkSRQwoSRQwsWVUEAWVUIAWVUIEWVUMAWVUMEWVUMIWVUQAWVUQEWVUQIWVUQMWVUYAWVUYEWVUYIWVUYMWVUYQWVUcAWVUcEWVUcIWVUcMWVUcQWVUcYWVUgAWVUgEWVUgIWVUgMWVUgQWVUgYWVUgcWVUkAWVUkEWVUkIWVUkMWVUkQWVUkYWVUkcWVUkgWVUoAWVUoEWVUoIWVUoMWVUoQWVUoYWVUocWVUogWVUokWVUsAWVUsEWVUsIWVUsMWVUsQWVUsYWVUscWVUsgWVUskWVUsoWVUwAWVUwEWVUwIWVUwMWVUwQWVUwYWVUwcWVUwgWVUwkWVUwoWVUwsaZYEAaZYIAaZYIEaZYMAaZYMEaZYMIaZYQAaZYQEaZYQIaZYQMaZYUAaZYUEaZYUIaZYUMaZYUQaZYcAaZYcEaZYcIaZYcMaZYcQaZYcUaZYgAaZYgEaZYgIaZYgMaZYgQaZYgUaZYgcaZYkAaZYkEaZYkIaZYkMaZYkQaZYkUaZYkcaZYkgaZYoAaZYoEaZYoIaZYoMaZYoQaZYoUaZYocaZYogaZYokaZYsAaZYsEaZYsIaZYsMaZYsQaZYsUaZYscaZYsgaZYskaZYsoaZYwAaZYwEaZYwIaZYwMaZYwQaZYwUaZYwcaZYwgaZYwkaZYwoaZYwsedcEAedcIAedcIEedcMAedcMEedcMIedcQAedcQEedcQIedcQMedcUAedcUEedcUIedcUMedcUQedcYAedcYEedcYIedcYMedcYQedcYUedcgAedcgEedcgIedcgMedcgQedcgUedcgYedckAedckEedckIedckMedckQedckUedckYedckgedcoAedcoEedcoIedcoMedcoQedcoUedcoYedcogedcokedcsAedcsEedcsIedcsMedcsQedcsUedcsYedcsgedcskedcsoedcwAedcwEedcwIedcwMedcwQedcwUedcwYedcwgedcwkedcwoedcwsihgEAihgIAihgIEihgMAihgMEihgMIihgQAihgQEihgQIihgQMihgUAihgUEihgUIihgUMihgUQihgYAihgYEihgYIihgYMihgYQihgYUihgcAihgcEihgcIihgcMihgcQihgcUihgcYihgkAihgkEihgkIihgkMihgkQihgkUihgkYihgkcihgoAihgoEihgoIihgoMihgoQihgoUihgoYihgocihgokihgsAihgsEihgsIihgsMihgsQihgsUihgsYihgscihgskihgsoihgwAihgwEihgwIihgwMihgwQihgwUihgwYihgwcihgwkihgwoihgwsmlkEAmlkIAmlkIEmlkMAmlkMEmlkMImlkQAmlkQEmlkQImlkQMmlkUAmlkUEmlkUImlkUMmlkUQmlkYAmlkYEmlkYImlkYMmlkYQmlkYUmlkcAmlkcEmlkcImlkcMmlkcQmlkcUmlkcYmlkgAmlkgEmlkgImlkgMmlkgQmlkgUmlkgYmlkgcmlkoAmlkoEmlkoImlkoMmlkoQmlkoUmlkoYmlkocmlkogmlksAmlksEmlksImlksMmlksQmlksUmlksYmlkscmlksgmlksomlkwAmlkwEmlkwImlkwMmlkwQmlkwUmlkwYmlkwcmlkwgmlkwomlkwsqpoEAqpoIAqpoIEqpoMAqpoMEqpoMIqpoQAqpoQEqpoQIqpoQMqpoUAqpoUEqpoUIqpoUMqpoUQqpoYAqpoYEqpoYIqpoYMqpoYQqpoYUqpocAqpocEqpocIqpocMqpocQqpocUqpocYqpogAqpogEqpogIqpogMqpogQqpogUqpogYqpogcqpokAqpokEqpokIqpokMqpokQqpokUqpokYqpokcqpokgqposAqposEqposIqposMqposQqposUqposYqposcqposgqposkqpowAqpowEqpowIqpowMqpowQqpowUqpowYqpowcqpowgqpowkqpowsutsEAutsIAutsIEutsMAutsMEutsMIutsQAutsQEutsQIutsQMutsUAutsUEutsUIutsUMutsUQutsYAutsYEutsYIutsYMutsYQutsYUutscAutscEutscIutscMutscQutscUutscYutsgAutsgEutsgIutsgMutsgQutsgUutsgYutsgcutskAutskEutskIutskMutskQutskUutskYutskcutskgutsoAutsoEutsoIutsoMutsoQutsoUutsoYutsocutsogutsokutswAutswEutswIutswMutswQutswUutswYutswcutswgutswkutswoyxwEAyxwIAyxwIEyxwMAyxwMEyxwMIyxwQAyxwQEyxwQIyxwQMyxwUAyxwUEyxwUIyxwUMyxwUQyxwYAyxwYEyxwYIyxwYMyxwYQyxwYUyxwcAyxwcEyxwcIyxwcMyxwcQyxwcUyxwcYyxwgAyxwgEyxwgIyxwgMyxwgQyxwgUyxwgYyxwgcyxwkAyxwkEyxwkIyxwkMyxwkQyxwkUyxwkYyxwkcyxwkgyxwoAyxwoEyxwoIyxwoMyxwoQyxwoUyxwoYyxwocyxwogyxwokyxwsAyxwsEyxwsIyxwsMyxwsQyxwsUyxwsYyxwscyxwsgyxwskyxwsoMIEBwQMIEBUQMIFYUQMJcYUQNgcYURkgcYVokgcZsokgdwsokhUMIEAUQIEAUQMEAUQMIAYMIEAYQIEAYQMEAYQMIAYQMIEYUIEAYUMEAYUMIAYUMIEYUQEAYUQIAYUQIEYUQMAYUQMEcMIEAcQIEAcQMEAcQMIAcQMIEcUIEAcUMEAcUMIAcUMIEcUQEAcUQIAcUQIEcUQMAcUQMEcUQMIcYIEAcYMEAcYMIAcYMIEcYQEAcYQIAcYQIEcYQMAcYQMEcYQMIcYUEAcYUIAcYUIEcYUMAcYUMEcYUMIcYUQAcYUQEcYUQIgMIEAgQIEAgQMEAgQMIAgQMIEgUIEAgUMEAgUMIAgUMIEgUQEAgUQIAgUQIEgUQMAgUQMEgUQMIgYIEAgYMEAgYMIAgYMIEgYQEAgYQIAgYQIEgYQMAgYQMEgYQMIgYUEAgYUIAgYUIEgYUMAgYUMEgYUMIgYUQAgYUQEgYUQIgYUQMgcIEAgcMEAgcMIAgcMIEgcQEAgcQIAgcQIEgcQMAgcQMEgcQMIgcUEAgcUIAgcUIEgcUMAgcUMEgcUMIgcUQAgcUQEgcUQIgcUQMgcYEAgcYIAgcYIEgcYMAgcYMEgcYMIgcYQAgcYQEgcYQIgcYQMgcYUAgcYUEgcYUIgcYUMkMIEAkQIEAkQMEAkQMIAkQMIEkUIEAkUMEAkUMIAkUMIEkUQEAkUQIAkUQIEkUQMAkUQMEkUQMIkYIEAkYMEAkYMIAkYMIEkYQEAkYQIAkYQIEkYQMAkYQMEkYQMIkYUEAkYUIAkYUIEkYUMAkYUMEkYUMIkYUQAkYUQEkYUQIkYUQMkcIEAkcMEAkcMIAkcMIEkcQEAkcQIAkcQIEkcQMAkcQMEkcQMIkcUEAkcUIAkcUIEkcUMAkcUMEkcUMIkcUQAkcUQEkcUQIkcUQMkcYEAkcYIAkcYIEkcYMAkcYMEkcYMIkcYQAkcYQEkcYQIkcYQMkcYUAkcYUEkcYUIkcYUMkcYUQkgIEAkgMEAkgMIAkgMIEkgQEAkgQIAkgQIEkgQMAkgQMEkgQMIkgUEAkgUIAkgUIEkgUMAkgUMEkgUMIkgUQAkgUQEkgUQIkgUQMkgYEAkgYIAkgYIEkgYMAkgYMEkgYMIkgYQAkgYQEkgYQIkgYQMkgYUAkgYUEkgYUIkgYUMkgYUQkgcEAkgcIAkgcIEkgcMAkgcMEkgcMIkgcQAkgcQEkgcQIkgcQMkgcUAkgcUEkgcUIkgcUMkgcUQkgcYAkgcYEkgcYIkgcYMkgcYQoMIEAoQIEAoQMEAoQMIAoQMIEoUIEAoUMEAoUMIAoUMIEoUQEAoUQIAoUQIEoUQMAoUQMEoUQMIoYIEAoYMEAoYMIAoYMIEoYQEAoYQIAoYQIEoYQMAoYQMEoYQMIoYUEAoYUIAoYUIEoYUMAoYUMEoYUMIoYUQAoYUQEoYUQIoYUQMocIEAocMEAocMIAocMIEocQEAocQIAocQIEocQMAocQMEocQMIocUEAocUIAocUIEocUMAocUMEocUMIocUQAocUQEocUQIocUQMocYEAocYIAocYIEocYMAocYMEocYMIocYQAocYQEocYQIocYQMocYUAocYUEocYUIocYUMocYUQogIEAogMEAogMIAogMIEogQEAogQIAogQIEogQMAogQMEogQMIogUEAogUIAogUIEogUMAogUMEogUMIogUQAogUQEogUQIogUQMogYEAogYIAogYIEogYMAogYMEogYMIogYQAogYQEogYQIogYQMogYUAogYUEogYUIogYUMogYUQogcEAogcIAogcIEogcMAogcMEogcMIogcQAogcQEogcQIogcQMogcUAogcUEogcUIogcUMogcUQogcYAogcYEogcYIogcYMogcYQogcYUokIEAokMEAokMIAokMIEokQEAokQIAokQIEokQMAokQMEokQMIokUEAokUIAokUIEokUMAokUMEokUMIokUQAokUQEokUQIokUQMokYEAokYIAokYIEokYMAokYMEokYMIokYQAokYQEokYQIokYQMokYUAokYUEokYUIokYUMokYUQokcEAokcIAokcIEokcMAokcMEokcMIokcQAokcQEokcQIokcQMokcUAokcUEokcUIokcUMokcUQokcYAokcYEokcYIokcYMokcYQokcYUokgEAokgIAokgIEokgMAokgMEokgMIokgQAokgQEokgQIokgQMokgUAokgUEokgUIokgUMokgUQokgYAokgYEokgYIokgYMokgYQokgYUokgcAokgcEokgcIokgcMokgcQokgcUsMIEAsQIEAsQMEAsQMIAsQMIEsUIEAsUMEAsUMIAsUMIEsUQEAsUQIAsUQIEsUQMAsUQMEsUQMIsYIEAsYMEAsYMIAsYMIEsYQEAsYQIAsYQIEsYQMAsYQMEsYQMIsYUEAsYUIAsYUIEsYUMAsYUMEsYUMIsYUQAsYUQEsYUQIsYUQMscIEAscMEAscMIAscMIEscQEAscQIAscQIEscQMAscQMEscQMIscUEAscUIAscUIEscUMAscUMEscUMIscUQAscUQEscUQIscUQMscYEAscYIAscYIEscYMAscYMEscYMIscYQAscYQEscYQIscYQMscYUAscYUEscYUIscYUMscYUQsgIEAsgMEAsgMIAsgMIEsgQEAsgQIAsgQIEsgQMAsgQMEsgQMIsgUEAsgUIAsgUIEsgUMAsgUMEsgUMIsgUQAsgUQEsgUQIsgUQMsgYEAsgYIAsgYIEsgYMAsgYMEsgYMIsgYQAsgYQEsgYQIsgYQMsgYUAsgYUEsgYUIsgYUMsgYUQsgcEAsgcIAsgcIEsgcMAsgcMEsgcMIsgcQAsgcQEsgcQIsgcQMsgcUAsgcUEsgcUIsgcUMsgcUQsgcYAsgcYEsgcYIsgcYMsgcYQsgcYUskIEAskMEAskMIAskMIEskQEAskQIAskQIEskQMAskQMEskQMIskUEAskUIAskUIEskUMAskUMEskUMIskUQAskUQEskUQIskUQMskYEAskYIAskYIEskYMAskYMEskYMIskYQAskYQEskYQIskYQMskYUAskYUEskYUIskYUMskYUQskcEAskcIAskcIEskcMAskcMEskcMIskcQAskcQEskcQIskcQMskcUAskcUEskcUIskcUMskcUQskcYAskcYEskcYIskcYMskcYQskcYUskgEAskgIAskgIEskgMAskgMEskgMIskgQAskgQEskgQIskgQMskgUAskgUEskgUIskgUMskgUQskgYAskgYEskgYIskgYMskgYQskgYUskgcAskgcEskgcIskgcMskgcQskgcUskgcYsoIEAsoMEAsoMIAsoMIEsoQEAsoQIAsoQIEsoQMAsoQMEsoQMIsoUEAsoUIAsoUIEsoUMAsoUMEsoUMIsoUQAsoUQEsoUQIsoUQMsoYEAsoYIAsoYIEsoYMAsoYMEsoYMIsoYQAsoYQEsoYQIsoYQMsoYUAsoYUEsoYUIsoYUMsoYUQsocEAsocIAsocIEsocMAsocMEsocMIsocQAsocQEsocQIsocQMsocUAsocUEsocUIsocUMsocUQsocYAsocYEsocYIsocYMsocYQsocYUsogEAsogIAsogIEsogMAsogMEsogMIsogQAsogQEsogQIsogQMsogUAsogUEsogUIsogUMsogUQsogYAsogYEsogYIsogYMsogYQsogYUsogcAsogcEsogcIsogcMsogcQsogcUsogcYsokEAsokIAsokIEsokMAsokMEsokMIsokQAsokQEsokQIsokQMsokUAsokUEsokUIsokUMsokUQsokYAsokYEsokYIsokYMsokYQsokYUsokcAsokcEsokcIsokcMsokcQsokcUsokcYsokgAsokgEsokgIsokgMsokgQsokgUsokgYwQIEAwQMEAwQMIAwQMIEwUIEAwUMEAwUMIAwUMIEwUQEAwUQIAwUQIEwUQMAwUQMEwUQMIwYIEAwYMEAwYMIAwYMIEwYQEAwYQIAwYQIEwYQMAwYQMEwYQMIwYUEAwYUIAwYUIEwYUMAwYUMEwYUMIwYUQAwYUQEwYUQIwYUQMwcIEAwcMEAwcMIAwcMIEwcQEAwcQIAwcQIEwcQMAwcQMEwcQMIwcUEAwcUIAwcUIEwcUMAwcUMEwcUMIwcUQAwcUQEwcUQIwcUQMwcYEAwcYIAwcYIEwcYMAwcYMEwcYMIwcYQAwcYQEwcYQIwcYQMwcYUAwcYUEwcYUIwcYUMwcYUQwgIEAwgMEAwgMIAwgMIEwgQEAwgQIAwgQIEwgQMAwgQMEwgQMIwgUEAwgUIAwgUIEwgUMAwgUMEwgUMIwgUQAwgUQEwgUQIwgUQMwgYEAwgYIAwgYIEwgYMAwgYMEwgYMIwgYQAwgYQEwgYQIwgYQMwgYUAwgYUEwgYUIwgYUMwgYUQwgcEAwgcIAwgcIEwgcMAwgcMEwgcMIwgcQAwgcQEwgcQIwgcQMwgcUAwgcUEwgcUIwgcUMwgcUQwgcYAwgcYEwgcYIwgcYMwgcYQwgcYUwkIEAwkMEAwkMIAwkMIEwkQEAwkQIAwkQIEwkQMAwkQMEwkQMIwkUEAwkUIAwkUIEwkUMAwkUMEwkUMIwkUQAwkUQEwkUQIwkUQMwkYEAwkYIAwkYIEwkYMAwkYMEwkYMIwkYQAwkYQEwkYQIwkYQMwkYUAwkYUEwkYUIwkYUMwkYUQwkcEAwkcIAwkcIEwkcMAwkcMEwkcMIwkcQAwkcQEwkcQIwkcQMwkcUAwkcUEwkcUIwkcUMwkcUQwkcYAwkcYEwkcYIwkcYMwkcYQwkcYUwkgEAwkgIAwkgIEwkgMAwkgMEwkgMIwkgQAwkgQEwkgQIwkgQMwkgUAwkgUEwkgUIwkgUMwkgUQwkgYAwkgYEwkgYIwkgYMwkgYQwkgYUwkgcAwkgcEwkgcIwkgcMwkgcQwkgcUwkgcYwoIEAwoMEAwoMIAwoMIEwoQEAwoQIAwoQIEwoQMAwoQMEwoQMIwoUEAwoUIAwoUIEwoUMAwoUMEwoUMIwoUQAwoUQEwoUQIwoUQMwoYEAwoYIAwoYIEwoYMAwoYMEwoYMIwoYQAwoYQEwoYQIwoYQMwoYUAwoYUEwoYUIwoYUMwoYUQwocEAwocIAwocIEwocMAwocMEwocMIwocQAwocQEwocQIwocQMwocUAwocUEwocUIwocUMwocUQwocYAwocYEwocYIwocYMwocYQwocYUwogEAwogIAwogIEwogMAwogMEwogMIwogQAwogQEwogQIwogQMwogUAwogUEwogUIwogUMwogUQwogYAwogYEwogYIwogYMwogYQwogYUwogcAwogcEwogcIwogcMwogcQwogcUwogcYwokEAwokIAwokIEwokMAwokMEwokMIwokQAwokQEwokQIwokQMwokUAwokUEwokUIwokUMwokUQwokYAwokYEwokYIwokYMwokYQwokYUwokcAwokcEwokcIwokcMwokcQwokcUwokcYwokgAwokgEwokgIwokgMwokgQwokgUwokgYwokgcwsIEAwsMEAwsMIAwsMIEwsQEAwsQIAwsQIEwsQMAwsQMEwsQMIwsUEAwsUIAwsUIEwsUMAwsUMEwsUMIwsUQAwsUQEwsUQIwsUQMwsYEAwsYIAwsYIEwsYMAwsYMEwsYMIwsYQAwsYQEwsYQIwsYQMwsYUAwsYUEwsYUIwsYUMwsYUQwscEAwscIAwscIEwscMAwscMEwscMIwscQAwscQEwscQIwscQMwscUAwscUEwscUIwscUMwscUQwscYAwscYEwscYIwscYMwscYQwscYUwsgEAwsgIAwsgIEwsgMAwsgMEwsgMIwsgQAwsgQEwsgQIwsgQMwsgUAwsgUEwsgUIwsgUMwsgUQwsgYAwsgYEwsgYIwsgYMwsgYQwsgYUwsgcAwsgcEwsgcIwsgcMwsgcQwsgcUwsgcYwskEAwskIAwskIEwskMAwskMEwskMIwskQAwskQEwskQIwskQMwskUAwskUEwskUIwskUMwskUQwskYAwskYEwskYIwskYMwskYQwskYUwskcAwskcEwskcIwskcMwskcQwskcUwskcYwskgAwskgEwskgIwskgMwskgQwskgUwskgYwskgcwsoEAwsoIAwsoIEwsoMAwsoMEwsoMIwsoQAwsoQEwsoQIwsoQMwsoUAwsoUEwsoUIwsoUMwsoUQwsoYAwsoYEwsoYIwsoYMwsoYQwsoYUwsocAwsocEwsocIwsocMwsocQwsocUwsocYwsogAwsogEwsogIwsogMwsogQwsogUwsogYwsogcwsokAwsokEwsokIwsokMwsokQwsokUwsokYwsokcCBAFECBAJICBANMCBARQCBAVUCBAZYCBAdcCBAhgCBAlkCBApoCBAtsCBAxwGFEBAGFEJIGFENMGFERQGFEVUGFEZYGFEdcGFEhgGFElkGFEpoGFEtsGFExwKJIBAKJIFEKJINMKJIRQKJIVUKJIZYKJIdcKJIhgKJIlkKJIpoKJItsKJIxwONMBAONMFEONMJIONMRQONMVUONMZYONMdcONMhgONMlkONMpoONMtsONMxwSRQBASRQFESRQJISRQNMSRQVUSRQZYSRQdcSRQhgSRQlkSRQpoSRQtsSRQxwWVUBAWVUFEWVUJIWVUNMWVURQWVUZYWVUdcWVUhgWVUlkWVUpoWVUtsWVUxwaZYBAaZYFEaZYJIaZYNMaZYRQaZYVUaZYdcaZYhgaZYlkaZYpoaZYtsaZYxwedcBAedcFEedcJIedcNMedcRQedcVUedcZYedchgedclkedcpoedctsedcxwihgBAihgFEihgJIihgNMihgRQihgVUihgZYihgdcihglkihgpoihgtsihgxwmlkBAmlkFEmlkJImlkNMmlkRQmlkVUmlkZYmlkdcmlkhgmlkpomlktsmlkxwqpoBAqpoFEqpoJIqpoNMqpoRQqpoVUqpoZYqpodcqpohgqpolkqpotsqpoxwutsBAutsFEutsJIutsNMutsRQutsVUutsZYutsdcutshgutslkutspoutsxwyxwBAyxwFEyxwJIyxwNMyxwRQyxwVUyxwZYyxwdcyxwhgyxwlkyxwpoyxwtsDCBAEDCBAIDCBAMDCBAQDCBAUDCBAYDCBAcDCBAgDCBAkDCBAoDCBAsDCBAwHGFEAHGFEIHGFEMHGFEQHGFEUHGFEYHGFEcHGFEgHGFEkHGFEoHGFEsHGFEwLKJIALKJIELKJIMLKJIQLKJIULKJIYLKJIcLKJIgLKJIkLKJIoLKJIsLKJIwPONMAPONMEPONMIPONMQPONMUPONMYPONMcPONMgPONMkPONMoPONMsPONMwTSRQATSRQETSRQITSRQMTSRQUTSRQYTSRQcTSRQgTSRQkTSRQoTSRQsTSRQwXWVUAXWVUEXWVUIXWVUMXWVUQXWVUYXWVUcXWVUgXWVUkXWVUoXWVUsXWVUwbaZYAbaZYEbaZYIbaZYMbaZYQbaZYUbaZYcbaZYgbaZYkbaZYobaZYsbaZYwfedcAfedcEfedcIfedcMfedcQfedcUfedcYfedcgfedckfedcofedcsfedcwjihgAjihgEjihgIjihgMjihgQjihgUjihgYjihgcjihgkjihgojihgsjihgwnmlkAnmlkEnmlkInmlkMnmlkQnmlkUnmlkYnmlkcnmlkgnmlkonmlksnmlkwrqpoArqpoErqpoIrqpoMrqpoQrqpoUrqpoYrqpocrqpogrqpokrqposrqpowvutsAvutsEvutsIvutsMvutsQvutsUvutsYvutscvutsgvutskvutsovutswzyxwAzyxwEzyxwIzyxwMzyxwQzyxwUzyxwYzyxwczyxwgzyxwkzyxwozyxwsMIEAwQMIEAUQMIEYUQMIcYUQMgcYUQkgcYUokgcYsokgcwsokg";

vector<Hand> vals;

const int n_vals = 7462;

void init_vals() {
  assert(str.size() == n_vals * 5);
  vals.reserve(n_vals);
  fore(i,0,n_vals) {
    array<Card,5> cards;
    fore(j,0,5) {
      cards[j] = toCard(str[i*5+j]);
    }
    vals[i] = Hand(cards);
  }
}

int solve(Hand hand) {
  fore(i,0,n_vals) {
    int c = cmp(hand,vals[i]);
    if (c == 0) {
      return i;
    }
  }
  assert(false);
}

int main(){
  ios::sync_with_stdio(0),cin.tie(0);
#ifdef ONLINE_JUDGE
  freopen("hands.in","r",stdin);
  freopen("hands.out","w",stdout);
#endif

  init_card_to_char();

/*   hardCode();
  return 0; */

  init_vals();

  array<Card,5> cards;
  fore(i,0,5) {
    cards[i] = readCard();
  }

  Hand hand(cards);

  cout << solve(hand) + 1 << '\n';
}
